Blender v4
UuuNyaa/blender_mmd_tools pull request #136
Opened 2024-03-28 08:40 UTC by kafuji

To adapt Blender 4.1's Mesh.use_auto_smooth and corresponding feature removals and changes,
and Pose.bone_groups -> Armature.collections changes, 
a little fixtures added to the code. It now properly exports PMX model. 
(I only fixed codes for PMX, therefore PMD codes still remain as is)

Additionally, fixed PMX Importer to properly works on Blendere 4.1. (Just skip use_auto_smooth=True)

2024-04-01 14:20 UTC, UuuNyaa requested changes
This branch does not need to support anything before Blender 4.1.
So please remove the `if bpy.app.version < (4, 1, 0)` cases.

2024-04-01 16:15 UTC, kafuji commented
Thank you for the review. Unfortunately I need backward compatibility for this. So I will simply close this request.

2024-04-01 16:15 UTC, closed without merging

2024-04-01 16:29 UTC, UuuNyaa commented
@kafuji Thank you for your reply 😀
I will refer to the code for the upcoming 4.2 LTS.

2024-04-09 15:40 UTC, read8873 commented
any chance for the support of 4.1 before May?